<?php
require_once 'config.php';
$page_title = 'Nexora — Digital Playground';
$products = db()->query("SELECT * FROM products WHERE is_active = 1 ORDER BY is_featured DESC, id DESC")->fetchAll();
include 'includes/header.php';
?>
<main>
<section class="hero container"><div class="hero-copy"><span class="eyebrow">Independent digital studio</span><h1>Fikirleri <em>dijitale</em><br> dönüştüren alan.</h1><p>Nexora; geliştiriciler, üreticiler ve meraklılar için seçilmiş dijital araçların ve işe yarayan fikirlerin buluşma noktası.</p><div class="hero-actions"><a class="primary-btn" href="#shop">Dijital ürünleri keşfet →</a><a class="secondary-btn" href="#explore">Canlı araçlara bak</a></div><div class="trust-row"><span>✓ Mobil uyumlu</span><span>♢ Güvenli üyelik</span><span>⚡ Canlı veriler</span></div></div><div class="live-card"><div class="live-top"><span><i></i> Canlı bağlam paneli</span><small>Europe / Istanbul</small></div><div class="live-grid"><div><label>◷ Yerel saat</label><strong id="live-clock">--:--</strong><small id="live-date">--</small></div><div><label>☁ Hava durumu</label><strong id="weather-temp">--°C</strong><small id="weather-label">Ankara yükleniyor…</small></div></div><div class="live-meta"><span id="weather-humidity">Nem --</span><span id="weather-wind">Rüzgâr --</span><span>⌖ Ankara</span></div></div></section>
<section id="explore" class="section container"><div class="section-intro"><span class="eyebrow">Canlı araçlar</span><h2>Her ziyaret biraz<br><em>daha faydalı olsun.</em></h2><p>Kısa araçlar, canlı veriler ve üretim odaklı dijital deneyimler.</p></div><div class="feature-grid"><article class="feature-card"><b>◷</b><h3>Canlı saat</h3><p>Ziyaretçiye bulunduğu zamanı ve saat dilimini gösterir.</p></article><article class="feature-card"><b>☁</b><h3>Ankara hava durumu</h3><p>Open-Meteo üzerinden Ankara için canlı veri alır.</p></article><article class="feature-card"><b>&lt;/&gt;</b><h3>Maker mindset</h3><p>Dijital ürünler, arayüz fikirleri ve deneysel araçlar.</p></article></div></section>
<section id="calculator" class="section container calculator-section"><div class="section-intro"><span class="eyebrow">Mini araç</span><h2>Hızlı bir <em>hesap.</em></h2><p>Basit işlemler için sayfadan ayrılmadan kullanabileceğin küçük hesap makinesi.</p></div><div class="panel calculator"><div class="calculator-row"><input id="calc-a" type="number" placeholder="İlk sayı"><select id="calc-op"><option value="+">+</option><option value="-">−</option><option value="*">×</option><option value="/">÷</option><option value="%">%</option></select><input id="calc-b" type="number" placeholder="İkinci sayı"><button class="primary-btn" id="calc-button" type="button">Hesapla</button></div><div class="calc-result">Sonuç: <strong id="calc-result">—</strong></div></div></section>
<section id="shop" class="section container"><div class="section-heading"><div><span class="eyebrow">Nexora shop</span><h2>İyi fikirlere <em>kısa yollar.</em></h2><p>Dijital toolkit’ler, arayüz sistemleri ve küçük servis paketleri.</p></div><span class="pill">Giriş yapınca sepete ekleyebilirsin</span></div><div class="product-grid"><?php if (!$products): ?><div class="empty-card">Henüz ürün eklenmedi. Admin hesabıyla <a href="admin.php">admin panelinden</a> ürün ekleyebilirsin.</div><?php endif; ?><?php foreach ($products as $product): ?><article class="product-card"><div class="product-top"><span class="product-icon"><?= e($product['icon']) ?></span><?php if ($product['is_featured']): ?><span class="pill accent">Öne çıkan</span><?php else: ?><span class="pill"><?= e($product['category']) ?></span><?php endif; ?></div><h3><?= e($product['name']) ?></h3><p><?= e($product['short_description']) ?></p><div class="product-bottom"><strong><?= money((int)$product['price_cents']) ?></strong><form method="post" action="cart.php"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="add"><input type="hidden" name="product_id" value="<?= (int)$product['id'] ?>"><button class="primary-btn small" type="submit">🛍 Sepete ekle</button></form></div><small>✓ Dijital teslim / güvenli sipariş</small></article><?php endforeach; ?></div></section>
<section id="feedback" class="section container feedback-section"><div class="section-intro"><span class="eyebrow">Sesini bırak</span><h2>Bir fikrin varsa,<br><em>masada yeri var.</em></h2><p>Şikâyet, öneri, iş birliği veya sadece selam. Mesajın veritabanına kaydedilir.</p></div><form class="panel feedback-form" method="post" action="feedback.php"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><div class="two-col"><label>Ad soyad<input name="name" required placeholder="Adın"></label><label>E-posta<input name="email" type="email" required placeholder="mail@example.com"></label></div><label>Konu<select name="type"><option value="suggestion">Öneri</option><option value="complaint">Şikâyet</option><option value="partnership">İş birliği</option><option value="other">Diğer</option></select></label><label>Mesaj<textarea name="message" required minlength="10" placeholder="Nexora hakkında ne düşünüyorsun?"></textarea></label><button class="primary-btn" type="submit">Mesajı gönder →</button></form></section>
</main>
<?php include 'includes/footer.php'; ?>
